FROM python:3.12.1

RUN pip install pandas pyarrow psycopg sqlalchemy

WORKDIR /app

COPY ../data/yellow_tripdata_2021-01.parquet /app/data

COPY postgres_ingestion.py postgres_ingestion.py

ENTRYPOINT [ "python", "postgres_ingestion.py"]